# Main Spring Settings
spring.application.name=goofy-irc-be
spring.output.ansi.enabled=always
spring.config.import=optional:file:.env[.properties]

# Main Server Settings
server.port=8443
spring.web.error.include-message=never
spring.devtools.add-properties=false

# General Data
goofy.general.frontend-url=https://fe.goofy-irc.rocc.systems
goofy.general.url=https://goofy-irc.rocc.systems
goofy.general.name=Goofy IRC
goofy.general.description=Goofy IRC Example Service for the Goofy Protocol
goofy.general.contact=Contact: real@mail.com
goofy.general.keypair.type=EC_C25519

# Registration
goofy.register.registrations-allowed=true
goofy.register.check-method=manual
goofy.register.auto-allow-domains=demo.fis.rocc.systems

# Rooms
goofy.room.max-rooms-per-user=5
goofy.room.default-max-user-limit=150

# Max Data sizes
goofy.auth.max-request-bytes=300000000
spring.servlet.multipart.max-file-size=250MB
spring.servlet.multipart.max-request-size=300MB

# Main H2 DB
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.h2.console.enabled=false
spring.datasource.url=jdbc:h2:/srv/data/irc_main.db;AUTO_SERVER=true
spring.datasource.username=sa
spring.datasource.password=sa

# Swagger
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false